// constants.js
export const GAMES = [
  {
    id: 1,
    title: "Maze Master",
    description: "Navigate through a challenging maze to find your way out.",
    cost: "10 Tokens",
    rewards: "NFT and up to 100 Tokens",
    image: "Maze.gif",
    url: "/games/maze",
  },
  {
    id: 2,
    title: "Memory Match",
    description: "Match cards to test your memory and win rewards.",
    cost: "5 Tokens",
    rewards: "Rare Frog NFTs and 50 Tokens",
    image: "/MemoryMatch.gif",
    url: "/games/memory-match",
  },
  {
    id: 3,
    title: "Snake Snack",
    description: "Control the snake to collect tokens and grow longer.",
    cost: "8 Tokens",
    rewards: "Exclusive NFTs and 80 Tokens",
    image: "/Snake.gif",
    url: "/games/snake",
  },
  {
    id: 4,
    title: "Ping Pong Pro",
    description: "Challenge your reflexes in a thrilling ping pong game.",
    cost: "6 Tokens",
    rewards: "Unique NFTs and 60 Tokens",
    image: "https://via.placeholder.com/150?text=Ping+Pong+Pro",
    url: "/games/ping-pong",
  },
  {
    id: 5,
    title: "Candy Sweeper",
    description: "Challenge your reflexes in a thrilling ping pong game.",
    cost: "6 Tokens",
    rewards: "Unique NFTs and 60 Tokens",
    image: "/CandyVsBomb1.gif",
    url: "/games/candy-minesweeper",
  },
];
